pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - #approved-reviews-by>=1
      - base=master
      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: merge
